#cloud-config
write_files:
  - content: |
      # Default server configuration
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
      }
    permissions: '0750'
    path: /etc/nginx.conf.cloud_init
  - content: |
      # run certbot
      until ping -c1 ${record-fqdn} &>/dev/null; do echo "waiting for dns record to initialise" ; sleep 3 ; done
      certbot run -n --nginx --agree-tos -d ${record-fqdn}  -m ${email} --redirect
    permissions: '0750'
    path: /etc/run_certbot
runcmd:
  - |
    until ping -c1 archive.ubuntu.com &>/dev/null; do echo "waiting for networking to initialise" ; sleep 3 ; done 
    export DEBIAN_FRONTEND=noninteractive
    apt-get -y update
    apt-get -y install certbot python3-certbot-nginx nginx
    systemctl stop nginx
    cp /etc/nginx/sites-available/default /etc/nginx.conf.apt
    [ -f /etc/nginx/sites-available/default ] && rm /etc/nginx/sites-available/default
    cp /etc/nginx.conf.cloud_init /etc/nginx/sites-available/default
    systemctl enable nginx
    systemctl stop nginx
    systemctl start nginx
    bash /etc/run_certbot
    systemctl stop nginx
    systemctl start nginx
packages_update: true
packages:
  - unzip
